### ISSUE TITLE
Referenzen zum Glossar von anderen Webseiten einholen 

### ISSUE THREAD

**Issue by theUpsider** [HASKI-Kempten/HASKI-Frontend#85]

**Comment by juli-txt** [comment]
## Verschiedene Beispiele zum Glossar:
1. Auflistung der Begrifflichkeiten mit ausfahrbarem Inhalt:
https://www.bundesfinanzministerium.de/Web/DE/Service/FAQ_Glossar/Glossar/Functions/glossar.html?lv2=f59e8c88-1592-444b-a813-c944663c56bf
2. Auflistung der Begrifflichkeiten mit Beschreibung direkt darunter:
https://www.idaev.de/recherchetools/glossar/
3. Auflistung der Begrifflichkeiten in einer Seitenleite:
https://www.dwd.de/DE/service/lexikon/Functions/glossar.html;jsessionid=62024A1BE016B1098F4BF6057448C6D1.live21072?nn=103346&lv2=100310&lv3=100376
4. Auflistung der Buchstaben mit ausfahrbarem Inhalt und darin enthaltener Auflistung der Begrifflichkeiten inklusive darunter liegender Beschreibung:
https://www.vodafone.de/hilfe/glossar.html
5. Tabellarische Darstellung der Begrifflichkeiten mit Beschreibung:
https://www.scribbr.de/aufbau-und-gliederung/das-glossar-einer-abschlussarbeit/
